version: "3"
services:

  nginx:
    build: nginx
    hostname: nginx
    ports:
      - "80:80"

  frontend:
    build: ./pizzato
    hostname: frontend
    image: pizzato-frontend:latest
    ports:
      - "3000:3000"

  backend:
    build: ./PizzatoWebApi/PizzatoWebApi
    hostname: backend
    image: pizzato-backend:latest
    ports:
      - "5000:5000"
