version: "3"
services:

  nginx:
    build: nginx
    ports:
      - "80:80"

  frontend:
    build: ./pizzato
    image: pizzato-frontend:latest
    ports:
      - "3000:3000"

  backend:
    build: ./PizzatoWebApi/PizzatoWebApi
    image: pizzato-backend:latest
    ports:
      - "5000:5000"
